---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-rs
  labels:
    app: spc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: myimage
          image: 9492453554/myimage3:latest
          ports:
          - containerPort: 8080
